### ISSUE TITLE
Incompatible with WebStorm 2016.2?

### ISSUE THREAD

**Issue by Granjow** [ideaflow/tools#2]
When I try to use the plugin with WebStorm 2016.2, it installs, but I can find neither buttons nor the New > IFM entry. Am I looking at the wrong place?

**Comment by accolasia** [comment]
By default the tools bar is hidden in later version of Intellij, and you have to goto View > Toolbar in the menu to turn the bar on.  Let me know if that works, I'm guessing that's the problem.

**Comment by accolasia** [comment]
Also, the best way to get support for the tools is to join openmastery.slack.com.  Reading through the experiences of a couple other people will probably save you some grief since they are a bit clunky right now.  I'll have to send you an invite though, if you want to email me at janelle@openmastery.org

**Comment by Granjow** [comment]
![2016-08-19 11_04_43-windows 8 x64 - vmware workstation](https://cloud.githubusercontent.com/assets/305622/17804619/c9a9fa2e-65fc-11e6-97ab-108d00fb85c4.png)
This is how it looks like now. Cannot see the tools there.

Thanks, will send you the email.

**Comment by accolasia** [comment]
Interesting.  I've never tried in webstorm, but we have a couple people that have it running in 2016.2 now and I wouldn't think it would be any different.   I'll download webstorm and try it out.

**Comment by accolasia** [comment]
I just downloaded webstorm, and I wasn't able to get the plugin to install.  I get an error message when adding the repository.  As far as I can tell from what you've shown me, the plugin was never successfully installed.  Did you get past this part?
<img width="428" alt="screenshot 2016-08-19 04 40 59" src="https://cloud.githubusercontent.com/assets/2080316/17805990/b3036ef2-65c7-11e6-9408-293d1cf1ce91.png">

**Comment by Granjow** [comment]
Funny. Yes, it shows up as installed:
![installed](https://cloud.githubusercontent.com/assets/305622/17806098/d68d4e70-6602-11e6-83be-29a2babe376a.png)

Just uninstalled and installed it again with the same result. Works (at least installing it).

**Comment by accolasia** [comment]
Hmm.  Are there any errors in your log file?  Maybe restart the IDE?

**Comment by accolasia** [comment]
The only other thing I can think of right now is that it's failing at startup with an exception and the plugin isn't getting loaded.  The plugin isn't that complicated.  I'm also wondering why I can't connect to the repo, but I'm glad you got past that part.

**Comment by accolasia** [comment]
I'm manually installing the zip so I can get past the weirdness with the repository not working...

**Comment by accolasia** [comment]
Well... the good news is that now I seem to be in the same state that you are in.  Tools installed fine but nothing shows up in right click menu or buttons.

**Comment by accolasia** [comment]
Okay, found the problem... in the log file: 
2016-08-19 05:27:21,072 [   1806]   INFO - llij.ide.plugins.PluginManager - Plugin 'Idea Flow' can't be loaded because: Plugin does not include any module dependency tags in its plugin.xml therefore is assumed legacy and can be loaded only in IntelliJ IDEA

**Comment by accolasia** [comment]
I'll work on getting a fix for this and keep you posted.

**Comment by Granjow** [comment]
Okay, thank you! :) Looking forward to testing it.

**Comment by accolasia** [comment]
Just uploaded the new version of the plugin 0.26 that's compatible with WebStorm. :)  Please note, you'll still need to run the visualizer webapp to open IFMs, but the plugin should work now.   ETA on the new MVP version of the tools is October -- the visualization and analytics tooling are moving to server side.

**Comment by Granjow** [comment]
Thank you! Just started working with it now :)
